// Generates src/lib/repos.ts from the tracked-repo list on disk, so the UI
// never hardcodes repos. A repo is "tracked" iff it has bedrock
// (guides/<repo>/overview.md) — committed content that's present in every build
// context (unlike the gitignored workspace/ the API derives from). Runs as the
// first step of `npm run build`, so manual builds and the serve.py watch-loop
// rebuild both pick up `just add-repo <repo>` automatically.
import { readdirSync, existsSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const WEB = join(dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = join(WEB, '..');
const GUIDES = join(ROOT, 'guides');
const OUT = join(WEB, 'src', 'lib', 'repos.ts');

// Curated display order; any newly-discovered repo is appended alphabetically.
const PREFERRED = ['jax', 'xla', 'orbax', 'tunix', 'tokamax'];

function discover() {
  if (!existsSync(GUIDES)) return PREFERRED;
  const found = readdirSync(GUIDES).filter((name) => {
    try {
      return statSync(join(GUIDES, name)).isDirectory()
        && existsSync(join(GUIDES, name, 'overview.md'));
    } catch {
      return false;
    }
  });
  if (!found.length) return PREFERRED;
  const extra = found.filter((r) => !PREFERRED.includes(r)).sort();
  return [...PREFERRED.filter((r) => found.includes(r)), ...extra];
}

const repos = discover();
const arr = repos.map((r) => `'${r}'`).join(', ');
const next = `// AUTO-GENERATED by web/scripts/gen-repos.mjs — do not edit by hand.
// Derived from guides/<repo>/overview.md at build time; mirrors the
// filesystem-derived list in scripts/serve.py so the UI and API agree.
// To add a repo, run \`just add-repo <org/repo>\` — the next build regenerates this.
export const REPOS = [${arr}] as const;
export type Repo = (typeof REPOS)[number];

export const isRepo = (s: string): s is Repo =>
  (REPOS as readonly string[]).includes(s);
`;

// Only write when changed — keeps the watch-loop rebuild from dirtying git on
// every content edit.
let prev = '';
try { prev = readFileSync(OUT, 'utf8'); } catch { /* first run */ }
if (prev !== next) {
  writeFileSync(OUT, next);
  console.log(`gen-repos: wrote ${repos.length} repos — ${repos.join(', ')}`);
} else {
  console.log(`gen-repos: unchanged (${repos.join(', ')})`);
}
