#!/usr/bin/env bash
# scripts/archive-sessions.sh — sessions/ retention. Session worknotes older
# than the retention window (default 60 days, by filename date) collapse into
# a per-month digest at sessions/archive/<YYYY-MM>-digest.md and the raw
# files are deleted. The digest keeps only what's worth keeping long-term:
# each session's frontmatter header, its artifact lines, and its
# "## chassis utilization" section — the tool-use log is dropped.
#
# Idempotent: archived files are gone, so a re-run finds nothing to redo;
# the digest is append-only. Run from maintenance.sh nightly or by hand.
#
# Usage:
#   scripts/archive-sessions.sh             # archive + delete
#   scripts/archive-sessions.sh --dry-run   # report what would be archived
#
# Tune the window: CARTOGRAPH_SESSION_RETAIN_DAYS=90

set -uo pipefail

source "$(dirname "$0")/lib/load-config.sh"
# shellcheck source=lib/errors.sh
source "$(dirname "$0")/lib/errors.sh"

SESSIONS_DIR="$CARTOGRAPH_ROOT/sessions"
ARCHIVE_DIR="$SESSIONS_DIR/archive"
RETAIN_DAYS="${CARTOGRAPH_SESSION_RETAIN_DAYS:-60}"

dry_run=0
[[ "${1:-}" == "--dry-run" ]] && dry_run=1

cutoff="$(python3 -c "import datetime; print((datetime.date.today() - datetime.timedelta(days=$RETAIN_DAYS)).isoformat())")"

# Emit one session's digest block on stdout: frontmatter (fenced), artifact
# lines, chassis-utilization section. Exits non-zero only on a read failure.
digest_block() {
  python3 - "$1" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
lines = path.read_text(encoding="utf-8", errors="replace").splitlines()

fm: list[str] = []
body_start = 0
if lines and lines[0].strip() == "---":
    for j in range(1, len(lines)):
        if lines[j].strip() == "---":
            fm = lines[1:j]
            body_start = j + 1
            break
body = lines[body_start:]


def section(name: str) -> list[str]:
    out: list[str] = []
    keep = False
    for ln in body:
        if ln.startswith("## "):
            keep = ln.strip().lower() == f"## {name}"
            continue
        if keep:
            out.append(ln)
    while out and not out[0].strip():
        out.pop(0)
    while out and not out[-1].strip():
        out.pop()
    return out


print(f"## {path.stem}")
print()
if fm:
    print("```yaml")
    print("\n".join(fm))
    print("```")
    print()
artifacts = section("artifacts produced")
if artifacts:
    print("### artifacts produced")
    print()
    print("\n".join(artifacts))
    print()
util = section("chassis utilization")
if util:
    print("### chassis utilization")
    print()
    print("\n".join(util))
    print()
PY
}

archived=0
for month_dir in "$SESSIONS_DIR"/[0-9][0-9][0-9][0-9]-[0-9][0-9]; do
  [[ -d "$month_dir" ]] || continue
  month="$(basename "$month_dir")"
  digest="$ARCHIVE_DIR/$month-digest.md"
  for f in "$month_dir"/*.md; do
    [[ -f "$f" ]] || continue
    name="$(basename "$f")"
    fdate="${name:0:10}"
    [[ "$fdate" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] || continue
    # ISO dates compare correctly as strings.
    [[ "$fdate" < "$cutoff" ]] || continue

    if (( dry_run )); then
      echo "would archive: sessions/$month/$name -> sessions/archive/$month-digest.md"
      archived=$((archived + 1))
      continue
    fi

    mkdir -p "$ARCHIVE_DIR"
    if [[ ! -f "$digest" ]]; then
      {
        echo "# sessions digest — $month"
        echo
        echo "Generated by scripts/archive-sessions.sh. Each archived session keeps"
        echo "its header, artifact lines, and chassis-utilization section; the raw"
        echo "worknote was deleted after archiving."
        echo
      } > "$digest"
    fi
    if digest_block "$f" >> "$digest"; then
      rm -f "$f"
      archived=$((archived + 1))
    else
      cg_log_error archive-sessions "failed to digest sessions/$month/$name — raw file kept"
    fi
  done
  # Drop month dirs emptied by archiving (rmdir refuses non-empty dirs).
  (( dry_run )) || rmdir "$month_dir" 2>/dev/null || true
done

if (( dry_run )); then
  echo "archive-sessions: would have archived $archived session(s) (cutoff $cutoff)"
else
  echo "archive-sessions: archived $archived session(s) (cutoff $cutoff)"
fi
